# put constants here
# example:
presence_thresh: 300
grasp:
  dir1_pin: board.D7
  dir2_pin: board.D8

stepper:
  mstep_pin1: board.D2
  mstep_pin2: board.D3
  mstep_pin3: board.D4
  step_pin: board.D5
  direction_pin: board.D6 


